spring:
  datasource:
    url: jdbc:h2:mem:testdb1
    #url=jdbc:h2:C:/git/restapi-sampledata:
    #url=jdbc:h2:file:/data/demo
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
