-- SQL create script
-- Must be named and placed exactly as: resources/schema.sql
-- You can copy-paste from H2 Hibernate test output and adjust for your needs
-- To make this working, you have to enable in application.properties:
-- spring.jpa.defer-datasource-initialization=true
select 1 ;

drop table if exists lesson CASCADE ;

drop table if exists student CASCADE ;

drop table if exists student_lesson CASCADE ;

create table lesson (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
) ;

create table student (
    id bigint generated by default as identity,
    active boolean not null,
    credits integer not null,
    name varchar(255),
    primary key (id)
) ;

create table student_lesson (
    student_id bigint not null,
    lesson_id bigint not null,
    primary key (student_id, lesson_id)
) ;

alter table student_lesson
    add constraint FKa64mwri6gq3ai7jwih91gsmf7
    foreign key (lesson_id)
    references lesson ;

alter table student_lesson
    add constraint FK2nmxs05vgk43xy1cko182p72p
    foreign key (student_id)
    references student ;

